/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ConnectionRequestId = IDL.Text;
export const ExerciseId = IDL.Nat;
export const UserId = IDL.Principal;
export const AppUserRole = IDL.Variant({
  'client' : IDL.Null,
  'admin' : IDL.Null,
  'trainer' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WorkoutPlanId = IDL.Text;
export const SetId = IDL.Nat;
export const Set = IDL.Record({
  'id' : SetId,
  'weight' : IDL.Float64,
  'exerciseId' : ExerciseId,
  'reps' : IDL.Nat,
});
export const Exercise = IDL.Record({
  'id' : ExerciseId,
  'difficultyLevel' : IDL.Text,
  'equipmentNeeded' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'recommendedSetsRange' : IDL.Text,
  'targetMuscleGroups' : IDL.Text,
  'videoUrl' : IDL.Text,
  'recommendedRepsRange' : IDL.Text,
});
export const FormAnalysisTip = IDL.Record({
  'exerciseId' : ExerciseId,
  'formCheckpoints' : IDL.Vec(IDL.Text),
  'commonMistakes' : IDL.Vec(IDL.Text),
  'correctionSteps' : IDL.Vec(IDL.Text),
  'videoUrl' : IDL.Text,
});
export const TimingGuideline = IDL.Record({
  'timing' : IDL.Text,
  'productName' : IDL.Text,
  'purpose' : IDL.Text,
});
export const SupplementProduct = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'productType' : IDL.Text,
});
export const DosageRecommendation = IDL.Record({
  'productName' : IDL.Text,
  'recommendedDosage' : IDL.Text,
});
export const SupplementStack = IDL.Record({
  'goalType' : IDL.Text,
  'timingGuidelines' : IDL.Vec(TimingGuideline),
  'benefitDescriptions' : IDL.Vec(IDL.Text),
  'products' : IDL.Vec(SupplementProduct),
  'dosageRecommendations' : IDL.Vec(DosageRecommendation),
});
export const User = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'role' : AppUserRole,
  'email' : IDL.Text,
});
export const BrandingSettings = IDL.Record({
  'primaryColor' : IDL.Text,
  'accentColor' : IDL.Text,
  'logoUrl' : IDL.Text,
  'secondaryColor' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : AppUserRole,
  'email' : IDL.Text,
});
export const WeightProgressionEntry = IDL.Record({
  'weight' : IDL.Float64,
  'exerciseId' : ExerciseId,
  'reps' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const ExerciseWithHistory = IDL.Record({
  'userHistory' : IDL.Opt(IDL.Vec(WeightProgressionEntry)),
  'exercise' : Exercise,
});
export const LocationPreference = IDL.Record({
  'latitude' : IDL.Float64,
  'gymName' : IDL.Text,
  'searchRadiusKm' : IDL.Nat,
  'userId' : UserId,
  'longitude' : IDL.Float64,
});
export const ConnectionRequest = IDL.Record({
  'id' : ConnectionRequestId,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  }),
  'receiverId' : UserId,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderId' : UserId,
});
export const NearbyUser = IDL.Record({
  'experienceLevel' : IDL.Text,
  'fitnessGoals' : IDL.Vec(IDL.Text),
  'userId' : UserId,
  'name' : IDL.Text,
  'distanceKm' : IDL.Float64,
});
export const OptimalWorkoutTime = IDL.Record({
  'recommendedEndTime' : IDL.Int,
  'userId' : UserId,
  'recommendedStartTime' : IDL.Int,
  'optimalWindow' : IDL.Nat,
});
export const PRLeaderboardEntry = IDL.Record({
  'weight' : IDL.Float64,
  'userId' : UserId,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'ranking' : IDL.Nat,
});
export const PrType = IDL.Variant({
  'deadlift' : IDL.Null,
  'benchPress' : IDL.Null,
  'shoulderPress' : IDL.Null,
  'squat' : IDL.Null,
  'barbellRow' : IDL.Null,
});
export const PRLeaderboard = IDL.Record({
  'entries' : IDL.Vec(PRLeaderboardEntry),
  'prType' : PrType,
});
export const WeightProgressionStats = IDL.Record({
  'totalVolume' : IDL.Float64,
  'exerciseId' : ExerciseId,
  'totalSets' : IDL.Nat,
  'averageWeight' : IDL.Float64,
  'totalSessions' : IDL.Nat,
  'suggestedIncrement' : IDL.Float64,
});
export const TrainingPartnerPreference = IDL.Record({
  'bio' : IDL.Text,
  'experienceLevel' : IDL.Text,
  'fitnessGoals' : IDL.Vec(IDL.Text),
  'preferredWorkoutTimes' : IDL.Vec(IDL.Text),
  'userId' : UserId,
});
export const RecordId = IDL.Text;
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptConnectionRequest' : IDL.Func([ConnectionRequestId], [], []),
  'addExerciseToLibrary' : IDL.Func(
      [
        ExerciseId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addUser' : IDL.Func([UserId, IDL.Text, IDL.Text, AppUserRole], [], []),
  'askVortex' : IDL.Func([IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignClientToTrainer' : IDL.Func([UserId, UserId], [], []),
  'clearCaffeineIntake' : IDL.Func([], [], []),
  'createWorkoutPlan' : IDL.Func(
      [
        WorkoutPlanId,
        UserId,
        UserId,
        IDL.Text,
        IDL.Vec(Set),
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'deleteExerciseFromLibrary' : IDL.Func([ExerciseId], [], []),
  'deleteWorkoutPlan' : IDL.Func([WorkoutPlanId], [], []),
  'editUser' : IDL.Func([UserId, IDL.Text, IDL.Text, AppUserRole], [], []),
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getAllFormAnalysisTips' : IDL.Func(
      [],
      [IDL.Vec(FormAnalysisTip)],
      ['query'],
    ),
  'getAllSupplementStacks' : IDL.Func(
      [],
      [IDL.Vec(SupplementStack)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getBrandingSettings' : IDL.Func([], [BrandingSettings], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExercise' : IDL.Func([ExerciseId], [IDL.Opt(Exercise)], ['query']),
  'getExerciseWithHistory' : IDL.Func(
      [ExerciseId],
      [IDL.Opt(ExerciseWithHistory)],
      ['query'],
    ),
  'getFormAnalysisTip' : IDL.Func(
      [ExerciseId],
      [IDL.Opt(FormAnalysisTip)],
      ['query'],
    ),
  'getLocationPreference' : IDL.Func(
      [],
      [IDL.Opt(LocationPreference)],
      ['query'],
    ),
  'getMyClients' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getMyConnectionRequests' : IDL.Func(
      [],
      [IDL.Vec(ConnectionRequest)],
      ['query'],
    ),
  'getMyConnections' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getNearbyUsers' : IDL.Func([], [IDL.Vec(NearbyUser)], ['query']),
  'getOptimalWorkoutTime' : IDL.Func(
      [],
      [IDL.Opt(OptimalWorkoutTime)],
      ['query'],
    ),
  'getPrLeaderboard' : IDL.Func([IDL.Int], [PRLeaderboard], ['query']),
  'getProgressionStatsForExercise' : IDL.Func(
      [ExerciseId],
      [WeightProgressionStats],
      ['query'],
    ),
  'getSupplementStack' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SupplementStack)],
      ['query'],
    ),
  'getTrainingPartnerPreference' : IDL.Func(
      [],
      [IDL.Opt(TrainingPartnerPreference)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeightProgressionEntries' : IDL.Func(
      [ExerciseId],
      [IDL.Vec(WeightProgressionEntry)],
      ['query'],
    ),
  'initializeFormAnalysisTipsAndSupplements' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logCaffeineIntake' : IDL.Func([IDL.Nat], [], []),
  'logWeightProgress' : IDL.Func([ExerciseId, IDL.Float64, IDL.Nat], [], []),
  'logWorkoutCompletion' : IDL.Func(
      [RecordId, WorkoutPlanId, UserId, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'rejectConnectionRequest' : IDL.Func([ConnectionRequestId], [], []),
  'removeUser' : IDL.Func([UserId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveLocationPreference' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'saveTrainingPartnerPreference' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'sendConnectionRequest' : IDL.Func(
      [UserId, IDL.Text],
      [ConnectionRequestId],
      [],
    ),
  'submitPersonalRecord' : IDL.Func([IDL.Int, IDL.Float64, IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBrandingSettings' : IDL.Func([BrandingSettings], [], []),
  'updateExerciseInLibrary' : IDL.Func(
      [
        ExerciseId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateWorkoutPlan' : IDL.Func(
      [WorkoutPlanId, IDL.Text, IDL.Vec(Set), IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ConnectionRequestId = IDL.Text;
  const ExerciseId = IDL.Nat;
  const UserId = IDL.Principal;
  const AppUserRole = IDL.Variant({
    'client' : IDL.Null,
    'admin' : IDL.Null,
    'trainer' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WorkoutPlanId = IDL.Text;
  const SetId = IDL.Nat;
  const Set = IDL.Record({
    'id' : SetId,
    'weight' : IDL.Float64,
    'exerciseId' : ExerciseId,
    'reps' : IDL.Nat,
  });
  const Exercise = IDL.Record({
    'id' : ExerciseId,
    'difficultyLevel' : IDL.Text,
    'equipmentNeeded' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'recommendedSetsRange' : IDL.Text,
    'targetMuscleGroups' : IDL.Text,
    'videoUrl' : IDL.Text,
    'recommendedRepsRange' : IDL.Text,
  });
  const FormAnalysisTip = IDL.Record({
    'exerciseId' : ExerciseId,
    'formCheckpoints' : IDL.Vec(IDL.Text),
    'commonMistakes' : IDL.Vec(IDL.Text),
    'correctionSteps' : IDL.Vec(IDL.Text),
    'videoUrl' : IDL.Text,
  });
  const TimingGuideline = IDL.Record({
    'timing' : IDL.Text,
    'productName' : IDL.Text,
    'purpose' : IDL.Text,
  });
  const SupplementProduct = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'productType' : IDL.Text,
  });
  const DosageRecommendation = IDL.Record({
    'productName' : IDL.Text,
    'recommendedDosage' : IDL.Text,
  });
  const SupplementStack = IDL.Record({
    'goalType' : IDL.Text,
    'timingGuidelines' : IDL.Vec(TimingGuideline),
    'benefitDescriptions' : IDL.Vec(IDL.Text),
    'products' : IDL.Vec(SupplementProduct),
    'dosageRecommendations' : IDL.Vec(DosageRecommendation),
  });
  const User = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'role' : AppUserRole,
    'email' : IDL.Text,
  });
  const BrandingSettings = IDL.Record({
    'primaryColor' : IDL.Text,
    'accentColor' : IDL.Text,
    'logoUrl' : IDL.Text,
    'secondaryColor' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : AppUserRole,
    'email' : IDL.Text,
  });
  const WeightProgressionEntry = IDL.Record({
    'weight' : IDL.Float64,
    'exerciseId' : ExerciseId,
    'reps' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const ExerciseWithHistory = IDL.Record({
    'userHistory' : IDL.Opt(IDL.Vec(WeightProgressionEntry)),
    'exercise' : Exercise,
  });
  const LocationPreference = IDL.Record({
    'latitude' : IDL.Float64,
    'gymName' : IDL.Text,
    'searchRadiusKm' : IDL.Nat,
    'userId' : UserId,
    'longitude' : IDL.Float64,
  });
  const ConnectionRequest = IDL.Record({
    'id' : ConnectionRequestId,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
      'accepted' : IDL.Null,
    }),
    'receiverId' : UserId,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderId' : UserId,
  });
  const NearbyUser = IDL.Record({
    'experienceLevel' : IDL.Text,
    'fitnessGoals' : IDL.Vec(IDL.Text),
    'userId' : UserId,
    'name' : IDL.Text,
    'distanceKm' : IDL.Float64,
  });
  const OptimalWorkoutTime = IDL.Record({
    'recommendedEndTime' : IDL.Int,
    'userId' : UserId,
    'recommendedStartTime' : IDL.Int,
    'optimalWindow' : IDL.Nat,
  });
  const PRLeaderboardEntry = IDL.Record({
    'weight' : IDL.Float64,
    'userId' : UserId,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'ranking' : IDL.Nat,
  });
  const PrType = IDL.Variant({
    'deadlift' : IDL.Null,
    'benchPress' : IDL.Null,
    'shoulderPress' : IDL.Null,
    'squat' : IDL.Null,
    'barbellRow' : IDL.Null,
  });
  const PRLeaderboard = IDL.Record({
    'entries' : IDL.Vec(PRLeaderboardEntry),
    'prType' : PrType,
  });
  const WeightProgressionStats = IDL.Record({
    'totalVolume' : IDL.Float64,
    'exerciseId' : ExerciseId,
    'totalSets' : IDL.Nat,
    'averageWeight' : IDL.Float64,
    'totalSessions' : IDL.Nat,
    'suggestedIncrement' : IDL.Float64,
  });
  const TrainingPartnerPreference = IDL.Record({
    'bio' : IDL.Text,
    'experienceLevel' : IDL.Text,
    'fitnessGoals' : IDL.Vec(IDL.Text),
    'preferredWorkoutTimes' : IDL.Vec(IDL.Text),
    'userId' : UserId,
  });
  const RecordId = IDL.Text;
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptConnectionRequest' : IDL.Func([ConnectionRequestId], [], []),
    'addExerciseToLibrary' : IDL.Func(
        [
          ExerciseId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addUser' : IDL.Func([UserId, IDL.Text, IDL.Text, AppUserRole], [], []),
    'askVortex' : IDL.Func([IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignClientToTrainer' : IDL.Func([UserId, UserId], [], []),
    'clearCaffeineIntake' : IDL.Func([], [], []),
    'createWorkoutPlan' : IDL.Func(
        [
          WorkoutPlanId,
          UserId,
          UserId,
          IDL.Text,
          IDL.Vec(Set),
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteExerciseFromLibrary' : IDL.Func([ExerciseId], [], []),
    'deleteWorkoutPlan' : IDL.Func([WorkoutPlanId], [], []),
    'editUser' : IDL.Func([UserId, IDL.Text, IDL.Text, AppUserRole], [], []),
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getAllFormAnalysisTips' : IDL.Func(
        [],
        [IDL.Vec(FormAnalysisTip)],
        ['query'],
      ),
    'getAllSupplementStacks' : IDL.Func(
        [],
        [IDL.Vec(SupplementStack)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getBrandingSettings' : IDL.Func([], [BrandingSettings], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExercise' : IDL.Func([ExerciseId], [IDL.Opt(Exercise)], ['query']),
    'getExerciseWithHistory' : IDL.Func(
        [ExerciseId],
        [IDL.Opt(ExerciseWithHistory)],
        ['query'],
      ),
    'getFormAnalysisTip' : IDL.Func(
        [ExerciseId],
        [IDL.Opt(FormAnalysisTip)],
        ['query'],
      ),
    'getLocationPreference' : IDL.Func(
        [],
        [IDL.Opt(LocationPreference)],
        ['query'],
      ),
    'getMyClients' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getMyConnectionRequests' : IDL.Func(
        [],
        [IDL.Vec(ConnectionRequest)],
        ['query'],
      ),
    'getMyConnections' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getNearbyUsers' : IDL.Func([], [IDL.Vec(NearbyUser)], ['query']),
    'getOptimalWorkoutTime' : IDL.Func(
        [],
        [IDL.Opt(OptimalWorkoutTime)],
        ['query'],
      ),
    'getPrLeaderboard' : IDL.Func([IDL.Int], [PRLeaderboard], ['query']),
    'getProgressionStatsForExercise' : IDL.Func(
        [ExerciseId],
        [WeightProgressionStats],
        ['query'],
      ),
    'getSupplementStack' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SupplementStack)],
        ['query'],
      ),
    'getTrainingPartnerPreference' : IDL.Func(
        [],
        [IDL.Opt(TrainingPartnerPreference)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeightProgressionEntries' : IDL.Func(
        [ExerciseId],
        [IDL.Vec(WeightProgressionEntry)],
        ['query'],
      ),
    'initializeFormAnalysisTipsAndSupplements' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logCaffeineIntake' : IDL.Func([IDL.Nat], [], []),
    'logWeightProgress' : IDL.Func([ExerciseId, IDL.Float64, IDL.Nat], [], []),
    'logWorkoutCompletion' : IDL.Func(
        [RecordId, WorkoutPlanId, UserId, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'rejectConnectionRequest' : IDL.Func([ConnectionRequestId], [], []),
    'removeUser' : IDL.Func([UserId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLocationPreference' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'saveTrainingPartnerPreference' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'sendConnectionRequest' : IDL.Func(
        [UserId, IDL.Text],
        [ConnectionRequestId],
        [],
      ),
    'submitPersonalRecord' : IDL.Func([IDL.Int, IDL.Float64, IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBrandingSettings' : IDL.Func([BrandingSettings], [], []),
    'updateExerciseInLibrary' : IDL.Func(
        [
          ExerciseId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateWorkoutPlan' : IDL.Func(
        [WorkoutPlanId, IDL.Text, IDL.Vec(Set), IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };