/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'client' : null } |
  { 'admin' : null } |
  { 'trainer' : null };
export interface BrandingSettings {
  'primaryColor' : string,
  'accentColor' : string,
  'logoUrl' : string,
  'secondaryColor' : string,
}
export interface DietOption {
  'foodItems' : Array<FoodItem>,
  'description' : string,
}
export interface DietPlan {
  'id' : DietPlanId,
  'meals' : Array<Meal>,
  'clientId' : UserId,
  'name' : string,
  'trainerId' : UserId,
  'dietaryNotes' : string,
}
export type DietPlanId = string;
export interface Exercise {
  'id' : ExerciseId,
  'difficultyLevel' : string,
  'equipmentNeeded' : string,
  'name' : string,
  'description' : string,
  'recommendedSetsRange' : string,
  'targetMuscleGroups' : string,
  'videoUrl' : string,
  'recommendedRepsRange' : string,
}
export type ExerciseId = bigint;
export interface FoodItem {
  'carbs' : number,
  'fats' : number,
  'calories' : bigint,
  'name' : string,
  'portion' : string,
  'protein' : number,
}
export interface Meal {
  'id' : MealId,
  'foodItems' : Array<FoodItem>,
  'carbs' : number,
  'fats' : number,
  'name' : string,
  'time' : string,
  'totalCalories' : bigint,
  'protein' : number,
}
export type MealId = string;
export interface MealOption {
  'options' : Array<DietOption>,
  'mealType' : string,
}
export type RecordId = string;
export interface ScheduledSession {
  'id' : TimetableId,
  'clientId' : UserId,
  'isCompleted' : boolean,
  'trainerNotes' : string,
  'trainerId' : UserId,
  'clientNotes' : string,
  'workoutPlanId' : WorkoutPlanId,
  'dateTime' : bigint,
}
export interface Set {
  'id' : SetId,
  'weight' : number,
  'exerciseId' : ExerciseId,
  'reps' : bigint,
}
export type SetId = bigint;
export type Time = bigint;
export type TimetableId = string;
export interface User {
  'id' : UserId,
  'name' : string,
  'role' : AppUserRole,
  'email' : string,
}
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'role' : AppUserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutPlan {
  'id' : WorkoutPlanId,
  'clientId' : UserId,
  'name' : string,
  'sets' : Array<Set>,
  'notes' : string,
  'restTime' : bigint,
  'creatorTrainerId' : UserId,
}
export type WorkoutPlanId = string;
export interface WorkoutRecord {
  'id' : RecordId,
  'completedSets' : bigint,
  'planId' : WorkoutPlanId,
  'userId' : UserId,
  'date' : Time,
  'personalNotes' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExerciseToLibrary' : ActorMethod<
    [
      ExerciseId,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'addUser' : ActorMethod<[UserId, string, string, AppUserRole], undefined>,
  'askVortex' : ActorMethod<[string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignClientToTrainer' : ActorMethod<[UserId, UserId], undefined>,
  'createDietPlan' : ActorMethod<
    [DietPlanId, UserId, UserId, string, Array<Meal>, string],
    undefined
  >,
  'createScheduledSession' : ActorMethod<
    [TimetableId, UserId, UserId, WorkoutPlanId, bigint, string],
    undefined
  >,
  'createWorkoutPlan' : ActorMethod<
    [WorkoutPlanId, UserId, UserId, string, Array<Set>, bigint, string],
    undefined
  >,
  'deleteDietPlan' : ActorMethod<[DietPlanId], undefined>,
  'deleteExerciseFromLibrary' : ActorMethod<[ExerciseId], undefined>,
  'deleteScheduledSession' : ActorMethod<[TimetableId], undefined>,
  'deleteWorkoutPlan' : ActorMethod<[WorkoutPlanId], undefined>,
  'editUser' : ActorMethod<[UserId, string, string, AppUserRole], undefined>,
  'getAllExercises' : ActorMethod<[], Array<Exercise>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAllWorkoutPlansForUser' : ActorMethod<[UserId], Array<WorkoutPlan>>,
  'getBrandingSettings' : ActorMethod<[], BrandingSettings>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDietPlanTemplate' : ActorMethod<[], Array<MealOption>>,
  'getDietPlansForClient' : ActorMethod<[UserId], Array<DietPlan>>,
  'getExercise' : ActorMethod<[ExerciseId], [] | [Exercise]>,
  'getScheduledSessionsForClient' : ActorMethod<
    [UserId],
    Array<ScheduledSession>
  >,
  'getScheduledSessionsForTrainer' : ActorMethod<
    [UserId],
    Array<ScheduledSession>
  >,
  'getTrainerClients' : ActorMethod<[UserId], Array<UserId>>,
  'getUser' : ActorMethod<[UserId], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkoutPlan' : ActorMethod<[WorkoutPlanId], [] | [WorkoutPlan]>,
  'getWorkoutRecordsForUser' : ActorMethod<[UserId], Array<WorkoutRecord>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logWorkoutCompletion' : ActorMethod<
    [RecordId, WorkoutPlanId, UserId, bigint, string],
    undefined
  >,
  'removeUser' : ActorMethod<[UserId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBrandingSettings' : ActorMethod<[BrandingSettings], undefined>,
  'updateDietPlan' : ActorMethod<[DietPlanId, Array<Meal>, string], undefined>,
  'updateExerciseInLibrary' : ActorMethod<
    [
      ExerciseId,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updateScheduledSession' : ActorMethod<
    [TimetableId, bigint, string],
    undefined
  >,
  'updateWorkoutPlan' : ActorMethod<
    [WorkoutPlanId, string, Array<Set>, bigint, string],
    undefined
  >,
  'updateWorkoutRecord' : ActorMethod<[RecordId, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];