/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'client' : null } |
  { 'admin' : null } |
  { 'trainer' : null };
export interface BrandingSettings {
  'primaryColor' : string,
  'accentColor' : string,
  'logoUrl' : string,
  'secondaryColor' : string,
}
export interface ConnectionRequest {
  'id' : ConnectionRequestId,
  'status' : { 'pending' : null } |
    { 'rejected' : null } |
    { 'accepted' : null },
  'receiverId' : UserId,
  'message' : string,
  'timestamp' : bigint,
  'senderId' : UserId,
}
export type ConnectionRequestId = string;
export interface DosageRecommendation {
  'productName' : string,
  'recommendedDosage' : string,
}
export interface Exercise {
  'id' : ExerciseId,
  'difficultyLevel' : string,
  'equipmentNeeded' : string,
  'name' : string,
  'description' : string,
  'recommendedSetsRange' : string,
  'targetMuscleGroups' : string,
  'videoUrl' : string,
  'recommendedRepsRange' : string,
}
export type ExerciseId = bigint;
export interface ExerciseWithHistory {
  'userHistory' : [] | [Array<WeightProgressionEntry>],
  'exercise' : Exercise,
}
export interface FormAnalysisTip {
  'exerciseId' : ExerciseId,
  'formCheckpoints' : Array<string>,
  'commonMistakes' : Array<string>,
  'correctionSteps' : Array<string>,
  'videoUrl' : string,
}
export interface LocationPreference {
  'latitude' : number,
  'gymName' : string,
  'searchRadiusKm' : bigint,
  'userId' : UserId,
  'longitude' : number,
}
export interface NearbyUser {
  'experienceLevel' : string,
  'fitnessGoals' : Array<string>,
  'userId' : UserId,
  'name' : string,
  'distanceKm' : number,
}
export interface OptimalWorkoutTime {
  'recommendedEndTime' : bigint,
  'userId' : UserId,
  'recommendedStartTime' : bigint,
  'optimalWindow' : bigint,
}
export type RecordId = string;
export interface Set {
  'id' : SetId,
  'weight' : number,
  'exerciseId' : ExerciseId,
  'reps' : bigint,
}
export type SetId = bigint;
export interface SupplementProduct {
  'name' : string,
  'description' : string,
  'productType' : string,
}
export interface SupplementStack {
  'goalType' : string,
  'timingGuidelines' : Array<TimingGuideline>,
  'benefitDescriptions' : Array<string>,
  'products' : Array<SupplementProduct>,
  'dosageRecommendations' : Array<DosageRecommendation>,
}
export interface TimingGuideline {
  'timing' : string,
  'productName' : string,
  'purpose' : string,
}
export interface TrainingPartnerPreference {
  'bio' : string,
  'experienceLevel' : string,
  'fitnessGoals' : Array<string>,
  'preferredWorkoutTimes' : Array<string>,
  'userId' : UserId,
}
export interface User {
  'id' : UserId,
  'name' : string,
  'role' : AppUserRole,
  'email' : string,
}
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'role' : AppUserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightProgressionEntry {
  'weight' : number,
  'exerciseId' : ExerciseId,
  'reps' : bigint,
  'timestamp' : bigint,
}
export interface WeightProgressionStats {
  'totalVolume' : number,
  'exerciseId' : ExerciseId,
  'totalSets' : bigint,
  'averageWeight' : number,
  'totalSessions' : bigint,
  'suggestedIncrement' : number,
}
export type WorkoutPlanId = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptConnectionRequest' : ActorMethod<[ConnectionRequestId], undefined>,
  'addExerciseToLibrary' : ActorMethod<
    [
      ExerciseId,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'addUser' : ActorMethod<[UserId, string, string, AppUserRole], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignClientToTrainer' : ActorMethod<[UserId, UserId], undefined>,
  'clearCaffeineIntake' : ActorMethod<[], undefined>,
  'createWorkoutPlan' : ActorMethod<
    [WorkoutPlanId, UserId, UserId, string, Array<Set>, bigint, string],
    undefined
  >,
  'deleteExerciseFromLibrary' : ActorMethod<[ExerciseId], undefined>,
  'deleteWorkoutPlan' : ActorMethod<[WorkoutPlanId], undefined>,
  'editUser' : ActorMethod<[UserId, string, string, AppUserRole], undefined>,
  'getAllExercises' : ActorMethod<[], Array<Exercise>>,
  'getAllFormAnalysisTips' : ActorMethod<[], Array<FormAnalysisTip>>,
  'getAllSupplementStacks' : ActorMethod<[], Array<SupplementStack>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getBrandingSettings' : ActorMethod<[], BrandingSettings>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExercise' : ActorMethod<[ExerciseId], [] | [Exercise]>,
  'getExerciseWithHistory' : ActorMethod<
    [ExerciseId],
    [] | [ExerciseWithHistory]
  >,
  'getFormAnalysisTip' : ActorMethod<[ExerciseId], [] | [FormAnalysisTip]>,
  'getLocationPreference' : ActorMethod<[], [] | [LocationPreference]>,
  'getMyClients' : ActorMethod<[], Array<User>>,
  'getMyConnectionRequests' : ActorMethod<[], Array<ConnectionRequest>>,
  'getMyConnections' : ActorMethod<[], Array<User>>,
  'getNearbyUsers' : ActorMethod<[], Array<NearbyUser>>,
  'getOptimalWorkoutTime' : ActorMethod<[], [] | [OptimalWorkoutTime]>,
  'getProgressionStatsForExercise' : ActorMethod<
    [ExerciseId],
    WeightProgressionStats
  >,
  'getSupplementStack' : ActorMethod<[string], [] | [SupplementStack]>,
  'getTrainingPartnerPreference' : ActorMethod<
    [],
    [] | [TrainingPartnerPreference]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeightProgressionEntries' : ActorMethod<
    [ExerciseId],
    Array<WeightProgressionEntry>
  >,
  'initializeFormAnalysisTipsAndSupplements' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logCaffeineIntake' : ActorMethod<[bigint], undefined>,
  'logWeightProgress' : ActorMethod<[ExerciseId, number, bigint], undefined>,
  'logWorkoutCompletion' : ActorMethod<
    [RecordId, WorkoutPlanId, UserId, bigint, string],
    undefined
  >,
  'rejectConnectionRequest' : ActorMethod<[ConnectionRequestId], undefined>,
  'removeUser' : ActorMethod<[UserId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLocationPreference' : ActorMethod<
    [number, number, bigint, string],
    undefined
  >,
  'saveTrainingPartnerPreference' : ActorMethod<
    [Array<string>, string, Array<string>, string],
    undefined
  >,
  'sendConnectionRequest' : ActorMethod<[UserId, string], ConnectionRequestId>,
  'updateBrandingSettings' : ActorMethod<[BrandingSettings], undefined>,
  'updateExerciseInLibrary' : ActorMethod<
    [
      ExerciseId,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updateWorkoutPlan' : ActorMethod<
    [WorkoutPlanId, string, Array<Set>, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];