/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExerciseId = IDL.Nat;
export const UserId = IDL.Principal;
export const AppUserRole = IDL.Variant({
  'client' : IDL.Null,
  'admin' : IDL.Null,
  'trainer' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DietPlanId = IDL.Text;
export const MealId = IDL.Text;
export const FoodItem = IDL.Record({
  'carbs' : IDL.Float64,
  'fats' : IDL.Float64,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'portion' : IDL.Text,
  'protein' : IDL.Float64,
});
export const Meal = IDL.Record({
  'id' : MealId,
  'foodItems' : IDL.Vec(FoodItem),
  'carbs' : IDL.Float64,
  'fats' : IDL.Float64,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'totalCalories' : IDL.Nat,
  'protein' : IDL.Float64,
});
export const TimetableId = IDL.Text;
export const WorkoutPlanId = IDL.Text;
export const SetId = IDL.Nat;
export const Set = IDL.Record({
  'id' : SetId,
  'weight' : IDL.Float64,
  'exerciseId' : ExerciseId,
  'reps' : IDL.Nat,
});
export const Exercise = IDL.Record({
  'id' : ExerciseId,
  'difficultyLevel' : IDL.Text,
  'equipmentNeeded' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'recommendedSetsRange' : IDL.Text,
  'targetMuscleGroups' : IDL.Text,
  'videoUrl' : IDL.Text,
  'recommendedRepsRange' : IDL.Text,
});
export const User = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'role' : AppUserRole,
  'email' : IDL.Text,
});
export const WorkoutPlan = IDL.Record({
  'id' : WorkoutPlanId,
  'clientId' : UserId,
  'name' : IDL.Text,
  'sets' : IDL.Vec(Set),
  'notes' : IDL.Text,
  'restTime' : IDL.Nat,
  'creatorTrainerId' : UserId,
});
export const BrandingSettings = IDL.Record({
  'primaryColor' : IDL.Text,
  'accentColor' : IDL.Text,
  'logoUrl' : IDL.Text,
  'secondaryColor' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : AppUserRole,
  'email' : IDL.Text,
});
export const DietOption = IDL.Record({
  'foodItems' : IDL.Vec(FoodItem),
  'description' : IDL.Text,
});
export const MealOption = IDL.Record({
  'options' : IDL.Vec(DietOption),
  'mealType' : IDL.Text,
});
export const DietPlan = IDL.Record({
  'id' : DietPlanId,
  'meals' : IDL.Vec(Meal),
  'clientId' : UserId,
  'name' : IDL.Text,
  'trainerId' : UserId,
  'dietaryNotes' : IDL.Text,
});
export const ScheduledSession = IDL.Record({
  'id' : TimetableId,
  'clientId' : UserId,
  'isCompleted' : IDL.Bool,
  'trainerNotes' : IDL.Text,
  'trainerId' : UserId,
  'clientNotes' : IDL.Text,
  'workoutPlanId' : WorkoutPlanId,
  'dateTime' : IDL.Int,
});
export const RecordId = IDL.Text;
export const Time = IDL.Int;
export const WorkoutRecord = IDL.Record({
  'id' : RecordId,
  'completedSets' : IDL.Nat,
  'planId' : WorkoutPlanId,
  'userId' : UserId,
  'date' : Time,
  'personalNotes' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExerciseToLibrary' : IDL.Func(
      [
        ExerciseId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addUser' : IDL.Func([UserId, IDL.Text, IDL.Text, AppUserRole], [], []),
  'askVortex' : IDL.Func([IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignClientToTrainer' : IDL.Func([UserId, UserId], [], []),
  'createDietPlan' : IDL.Func(
      [DietPlanId, UserId, UserId, IDL.Text, IDL.Vec(Meal), IDL.Text],
      [],
      [],
    ),
  'createScheduledSession' : IDL.Func(
      [TimetableId, UserId, UserId, WorkoutPlanId, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'createWorkoutPlan' : IDL.Func(
      [
        WorkoutPlanId,
        UserId,
        UserId,
        IDL.Text,
        IDL.Vec(Set),
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'deleteDietPlan' : IDL.Func([DietPlanId], [], []),
  'deleteExerciseFromLibrary' : IDL.Func([ExerciseId], [], []),
  'deleteScheduledSession' : IDL.Func([TimetableId], [], []),
  'deleteWorkoutPlan' : IDL.Func([WorkoutPlanId], [], []),
  'editUser' : IDL.Func([UserId, IDL.Text, IDL.Text, AppUserRole], [], []),
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAllWorkoutPlansForUser' : IDL.Func(
      [UserId],
      [IDL.Vec(WorkoutPlan)],
      ['query'],
    ),
  'getBrandingSettings' : IDL.Func([], [BrandingSettings], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDietPlanTemplate' : IDL.Func([], [IDL.Vec(MealOption)], ['query']),
  'getDietPlansForClient' : IDL.Func([UserId], [IDL.Vec(DietPlan)], ['query']),
  'getExercise' : IDL.Func([ExerciseId], [IDL.Opt(Exercise)], ['query']),
  'getScheduledSessionsForClient' : IDL.Func(
      [UserId],
      [IDL.Vec(ScheduledSession)],
      ['query'],
    ),
  'getScheduledSessionsForTrainer' : IDL.Func(
      [UserId],
      [IDL.Vec(ScheduledSession)],
      ['query'],
    ),
  'getTrainerClients' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkoutPlan' : IDL.Func(
      [WorkoutPlanId],
      [IDL.Opt(WorkoutPlan)],
      ['query'],
    ),
  'getWorkoutRecordsForUser' : IDL.Func(
      [UserId],
      [IDL.Vec(WorkoutRecord)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWorkoutCompletion' : IDL.Func(
      [RecordId, WorkoutPlanId, UserId, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'removeUser' : IDL.Func([UserId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBrandingSettings' : IDL.Func([BrandingSettings], [], []),
  'updateDietPlan' : IDL.Func([DietPlanId, IDL.Vec(Meal), IDL.Text], [], []),
  'updateExerciseInLibrary' : IDL.Func(
      [
        ExerciseId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateScheduledSession' : IDL.Func([TimetableId, IDL.Int, IDL.Text], [], []),
  'updateWorkoutPlan' : IDL.Func(
      [WorkoutPlanId, IDL.Text, IDL.Vec(Set), IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateWorkoutRecord' : IDL.Func([RecordId, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExerciseId = IDL.Nat;
  const UserId = IDL.Principal;
  const AppUserRole = IDL.Variant({
    'client' : IDL.Null,
    'admin' : IDL.Null,
    'trainer' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DietPlanId = IDL.Text;
  const MealId = IDL.Text;
  const FoodItem = IDL.Record({
    'carbs' : IDL.Float64,
    'fats' : IDL.Float64,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'portion' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const Meal = IDL.Record({
    'id' : MealId,
    'foodItems' : IDL.Vec(FoodItem),
    'carbs' : IDL.Float64,
    'fats' : IDL.Float64,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'totalCalories' : IDL.Nat,
    'protein' : IDL.Float64,
  });
  const TimetableId = IDL.Text;
  const WorkoutPlanId = IDL.Text;
  const SetId = IDL.Nat;
  const Set = IDL.Record({
    'id' : SetId,
    'weight' : IDL.Float64,
    'exerciseId' : ExerciseId,
    'reps' : IDL.Nat,
  });
  const Exercise = IDL.Record({
    'id' : ExerciseId,
    'difficultyLevel' : IDL.Text,
    'equipmentNeeded' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'recommendedSetsRange' : IDL.Text,
    'targetMuscleGroups' : IDL.Text,
    'videoUrl' : IDL.Text,
    'recommendedRepsRange' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'role' : AppUserRole,
    'email' : IDL.Text,
  });
  const WorkoutPlan = IDL.Record({
    'id' : WorkoutPlanId,
    'clientId' : UserId,
    'name' : IDL.Text,
    'sets' : IDL.Vec(Set),
    'notes' : IDL.Text,
    'restTime' : IDL.Nat,
    'creatorTrainerId' : UserId,
  });
  const BrandingSettings = IDL.Record({
    'primaryColor' : IDL.Text,
    'accentColor' : IDL.Text,
    'logoUrl' : IDL.Text,
    'secondaryColor' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : AppUserRole,
    'email' : IDL.Text,
  });
  const DietOption = IDL.Record({
    'foodItems' : IDL.Vec(FoodItem),
    'description' : IDL.Text,
  });
  const MealOption = IDL.Record({
    'options' : IDL.Vec(DietOption),
    'mealType' : IDL.Text,
  });
  const DietPlan = IDL.Record({
    'id' : DietPlanId,
    'meals' : IDL.Vec(Meal),
    'clientId' : UserId,
    'name' : IDL.Text,
    'trainerId' : UserId,
    'dietaryNotes' : IDL.Text,
  });
  const ScheduledSession = IDL.Record({
    'id' : TimetableId,
    'clientId' : UserId,
    'isCompleted' : IDL.Bool,
    'trainerNotes' : IDL.Text,
    'trainerId' : UserId,
    'clientNotes' : IDL.Text,
    'workoutPlanId' : WorkoutPlanId,
    'dateTime' : IDL.Int,
  });
  const RecordId = IDL.Text;
  const Time = IDL.Int;
  const WorkoutRecord = IDL.Record({
    'id' : RecordId,
    'completedSets' : IDL.Nat,
    'planId' : WorkoutPlanId,
    'userId' : UserId,
    'date' : Time,
    'personalNotes' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExerciseToLibrary' : IDL.Func(
        [
          ExerciseId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addUser' : IDL.Func([UserId, IDL.Text, IDL.Text, AppUserRole], [], []),
    'askVortex' : IDL.Func([IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignClientToTrainer' : IDL.Func([UserId, UserId], [], []),
    'createDietPlan' : IDL.Func(
        [DietPlanId, UserId, UserId, IDL.Text, IDL.Vec(Meal), IDL.Text],
        [],
        [],
      ),
    'createScheduledSession' : IDL.Func(
        [TimetableId, UserId, UserId, WorkoutPlanId, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'createWorkoutPlan' : IDL.Func(
        [
          WorkoutPlanId,
          UserId,
          UserId,
          IDL.Text,
          IDL.Vec(Set),
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteDietPlan' : IDL.Func([DietPlanId], [], []),
    'deleteExerciseFromLibrary' : IDL.Func([ExerciseId], [], []),
    'deleteScheduledSession' : IDL.Func([TimetableId], [], []),
    'deleteWorkoutPlan' : IDL.Func([WorkoutPlanId], [], []),
    'editUser' : IDL.Func([UserId, IDL.Text, IDL.Text, AppUserRole], [], []),
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAllWorkoutPlansForUser' : IDL.Func(
        [UserId],
        [IDL.Vec(WorkoutPlan)],
        ['query'],
      ),
    'getBrandingSettings' : IDL.Func([], [BrandingSettings], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDietPlanTemplate' : IDL.Func([], [IDL.Vec(MealOption)], ['query']),
    'getDietPlansForClient' : IDL.Func(
        [UserId],
        [IDL.Vec(DietPlan)],
        ['query'],
      ),
    'getExercise' : IDL.Func([ExerciseId], [IDL.Opt(Exercise)], ['query']),
    'getScheduledSessionsForClient' : IDL.Func(
        [UserId],
        [IDL.Vec(ScheduledSession)],
        ['query'],
      ),
    'getScheduledSessionsForTrainer' : IDL.Func(
        [UserId],
        [IDL.Vec(ScheduledSession)],
        ['query'],
      ),
    'getTrainerClients' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkoutPlan' : IDL.Func(
        [WorkoutPlanId],
        [IDL.Opt(WorkoutPlan)],
        ['query'],
      ),
    'getWorkoutRecordsForUser' : IDL.Func(
        [UserId],
        [IDL.Vec(WorkoutRecord)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWorkoutCompletion' : IDL.Func(
        [RecordId, WorkoutPlanId, UserId, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'removeUser' : IDL.Func([UserId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBrandingSettings' : IDL.Func([BrandingSettings], [], []),
    'updateDietPlan' : IDL.Func([DietPlanId, IDL.Vec(Meal), IDL.Text], [], []),
    'updateExerciseInLibrary' : IDL.Func(
        [
          ExerciseId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateScheduledSession' : IDL.Func(
        [TimetableId, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'updateWorkoutPlan' : IDL.Func(
        [WorkoutPlanId, IDL.Text, IDL.Vec(Set), IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateWorkoutRecord' : IDL.Func([RecordId, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };