/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TrainingPartnerPreference {
    bio: string;
    experienceLevel: string;
    fitnessGoals: Array<string>;
    preferredWorkoutTimes: Array<string>;
    userId: UserId;
}
export type RecordId = string;
export interface FormAnalysisTip {
    exerciseId: ExerciseId;
    formCheckpoints: Array<string>;
    commonMistakes: Array<string>;
    correctionSteps: Array<string>;
    videoUrl: string;
}
export interface SupplementStack {
    goalType: string;
    timingGuidelines: Array<TimingGuideline>;
    benefitDescriptions: Array<string>;
    products: Array<SupplementProduct>;
    dosageRecommendations: Array<DosageRecommendation>;
}
export type WorkoutPlanId = string;
export interface LocationPreference {
    latitude: number;
    gymName: string;
    searchRadiusKm: bigint;
    userId: UserId;
    longitude: number;
}
export interface ConnectionRequest {
    id: ConnectionRequestId;
    status: Variant_pending_rejected_accepted;
    receiverId: UserId;
    message: string;
    timestamp: bigint;
    senderId: UserId;
}
export type ExerciseId = bigint;
export type ConnectionRequestId = string;
export interface BrandingSettings {
    primaryColor: string;
    accentColor: string;
    logoUrl: string;
    secondaryColor: string;
}
export interface Exercise {
    id: ExerciseId;
    difficultyLevel: string;
    equipmentNeeded: string;
    name: string;
    description: string;
    recommendedSetsRange: string;
    targetMuscleGroups: string;
    videoUrl: string;
    recommendedRepsRange: string;
}
export interface User {
    id: UserId;
    name: string;
    role: AppUserRole;
    email: string;
}
export interface DosageRecommendation {
    productName: string;
    recommendedDosage: string;
}
export interface WeightProgressionEntry {
    weight: number;
    exerciseId: ExerciseId;
    reps: bigint;
    timestamp: bigint;
}
export interface OptimalWorkoutTime {
    recommendedEndTime: bigint;
    userId: UserId;
    recommendedStartTime: bigint;
    optimalWindow: bigint;
}
export interface SupplementProduct {
    name: string;
    description: string;
    productType: string;
}
export interface WeightProgressionStats {
    totalVolume: number;
    exerciseId: ExerciseId;
    totalSets: bigint;
    averageWeight: number;
    totalSessions: bigint;
    suggestedIncrement: number;
}
export interface Set_ {
    id: SetId;
    weight: number;
    exerciseId: ExerciseId;
    reps: bigint;
}
export type UserId = Principal;
export interface NearbyUser {
    experienceLevel: string;
    fitnessGoals: Array<string>;
    userId: UserId;
    name: string;
    distanceKm: number;
}
export interface ExerciseWithHistory {
    userHistory?: Array<WeightProgressionEntry>;
    exercise: Exercise;
}
export interface TimingGuideline {
    timing: string;
    productName: string;
    purpose: string;
}
export type SetId = bigint;
export interface UserProfile {
    name: string;
    role: AppUserRole;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AppUserRole {
    client = "client",
    admin = "admin",
    trainer = "trainer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_rejected_accepted {
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptConnectionRequest(requestId: ConnectionRequestId): Promise<void>;
    addExerciseToLibrary(id: ExerciseId, name: string, targetMuscleGroups: string, difficultyLevel: string, equipmentNeeded: string, videoUrl: string, description: string, recommendedRepsRange: string, recommendedSetsRange: string): Promise<void>;
    addUser(id: UserId, name: string, email: string, role: AppUserRole): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignClientToTrainer(trainerId: UserId, clientId: UserId): Promise<void>;
    clearCaffeineIntake(): Promise<void>;
    createWorkoutPlan(planId: WorkoutPlanId, trainerId: UserId, clientId: UserId, name: string, sets: Array<Set_>, restTime: bigint, notes: string): Promise<void>;
    deleteExerciseFromLibrary(id: ExerciseId): Promise<void>;
    deleteWorkoutPlan(planId: WorkoutPlanId): Promise<void>;
    editUser(id: UserId, name: string, email: string, role: AppUserRole): Promise<void>;
    getAllExercises(): Promise<Array<Exercise>>;
    getAllFormAnalysisTips(): Promise<Array<FormAnalysisTip>>;
    getAllSupplementStacks(): Promise<Array<SupplementStack>>;
    getAllUsers(): Promise<Array<User>>;
    getBrandingSettings(): Promise<BrandingSettings>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExercise(id: ExerciseId): Promise<Exercise | null>;
    getExerciseWithHistory(id: ExerciseId): Promise<ExerciseWithHistory | null>;
    getFormAnalysisTip(exerciseId: ExerciseId): Promise<FormAnalysisTip | null>;
    getLocationPreference(): Promise<LocationPreference | null>;
    getMyClients(): Promise<Array<User>>;
    getMyConnectionRequests(): Promise<Array<ConnectionRequest>>;
    getMyConnections(): Promise<Array<User>>;
    getNearbyUsers(): Promise<Array<NearbyUser>>;
    getOptimalWorkoutTime(): Promise<OptimalWorkoutTime | null>;
    getProgressionStatsForExercise(exerciseId: ExerciseId): Promise<WeightProgressionStats>;
    getSupplementStack(goalType: string): Promise<SupplementStack | null>;
    getTrainingPartnerPreference(): Promise<TrainingPartnerPreference | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeightProgressionEntries(exerciseId: ExerciseId): Promise<Array<WeightProgressionEntry>>;
    initializeFormAnalysisTipsAndSupplements(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    logCaffeineIntake(amountMg: bigint): Promise<void>;
    logWeightProgress(exerciseId: ExerciseId, weight: number, reps: bigint): Promise<void>;
    logWorkoutCompletion(recordId: RecordId, planId: WorkoutPlanId, userId: UserId, completedSets: bigint, personalNotes: string): Promise<void>;
    rejectConnectionRequest(requestId: ConnectionRequestId): Promise<void>;
    removeUser(id: UserId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveLocationPreference(latitude: number, longitude: number, searchRadiusKm: bigint, gymName: string): Promise<void>;
    saveTrainingPartnerPreference(fitnessGoals: Array<string>, experienceLevel: string, preferredWorkoutTimes: Array<string>, bio: string): Promise<void>;
    sendConnectionRequest(receiverId: UserId, message: string): Promise<ConnectionRequestId>;
    updateBrandingSettings(newSettings: BrandingSettings): Promise<void>;
    updateExerciseInLibrary(id: ExerciseId, name: string, targetMuscleGroups: string, difficultyLevel: string, equipmentNeeded: string, videoUrl: string, description: string, recommendedRepsRange: string, recommendedSetsRange: string): Promise<void>;
    updateWorkoutPlan(planId: WorkoutPlanId, name: string, sets: Array<Set_>, restTime: bigint, notes: string): Promise<void>;
}
import type { AppUserRole as _AppUserRole, ConnectionRequest as _ConnectionRequest, ConnectionRequestId as _ConnectionRequestId, Exercise as _Exercise, ExerciseWithHistory as _ExerciseWithHistory, FormAnalysisTip as _FormAnalysisTip, LocationPreference as _LocationPreference, OptimalWorkoutTime as _OptimalWorkoutTime, SupplementStack as _SupplementStack, TrainingPartnerPreference as _TrainingPartnerPreference, User as _User, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, WeightProgressionEntry as _WeightProgressionEntry, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptConnectionRequest(arg0: ConnectionRequestId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptConnectionRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptConnectionRequest(arg0);
            return result;
        }
    }
    async addExerciseToLibrary(arg0: ExerciseId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExerciseToLibrary(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExerciseToLibrary(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async addUser(arg0: UserId, arg1: string, arg2: string, arg3: AppUserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0, arg1, arg2, to_candid_AppUserRole_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0, arg1, arg2, to_candid_AppUserRole_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignClientToTrainer(arg0: UserId, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignClientToTrainer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignClientToTrainer(arg0, arg1);
            return result;
        }
    }
    async clearCaffeineIntake(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCaffeineIntake();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCaffeineIntake();
            return result;
        }
    }
    async createWorkoutPlan(arg0: WorkoutPlanId, arg1: UserId, arg2: UserId, arg3: string, arg4: Array<Set_>, arg5: bigint, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkoutPlan(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkoutPlan(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteExerciseFromLibrary(arg0: ExerciseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExerciseFromLibrary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExerciseFromLibrary(arg0);
            return result;
        }
    }
    async deleteWorkoutPlan(arg0: WorkoutPlanId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkoutPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkoutPlan(arg0);
            return result;
        }
    }
    async editUser(arg0: UserId, arg1: string, arg2: string, arg3: AppUserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editUser(arg0, arg1, arg2, to_candid_AppUserRole_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editUser(arg0, arg1, arg2, to_candid_AppUserRole_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getAllExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExercises();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExercises();
            return result;
        }
    }
    async getAllFormAnalysisTips(): Promise<Array<FormAnalysisTip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFormAnalysisTips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFormAnalysisTips();
            return result;
        }
    }
    async getAllSupplementStacks(): Promise<Array<SupplementStack>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSupplementStacks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSupplementStacks();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBrandingSettings(): Promise<BrandingSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrandingSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrandingSettings();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExercise(arg0: ExerciseId): Promise<Exercise | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercise(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercise(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExerciseWithHistory(arg0: ExerciseId): Promise<ExerciseWithHistory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExerciseWithHistory(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExerciseWithHistory(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFormAnalysisTip(arg0: ExerciseId): Promise<FormAnalysisTip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFormAnalysisTip(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFormAnalysisTip(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocationPreference(): Promise<LocationPreference | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocationPreference();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocationPreference();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyClients(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyClients();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyClients();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyConnectionRequests(): Promise<Array<ConnectionRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyConnectionRequests();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyConnectionRequests();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyConnections(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyConnections();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyConnections();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNearbyUsers(): Promise<Array<NearbyUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearbyUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearbyUsers();
            return result;
        }
    }
    async getOptimalWorkoutTime(): Promise<OptimalWorkoutTime | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOptimalWorkoutTime();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOptimalWorkoutTime();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgressionStatsForExercise(arg0: ExerciseId): Promise<WeightProgressionStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressionStatsForExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressionStatsForExercise(arg0);
            return result;
        }
    }
    async getSupplementStack(arg0: string): Promise<SupplementStack | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplementStack(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplementStack(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrainingPartnerPreference(): Promise<TrainingPartnerPreference | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingPartnerPreference();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingPartnerPreference();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeightProgressionEntries(arg0: ExerciseId): Promise<Array<WeightProgressionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightProgressionEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightProgressionEntries(arg0);
            return result;
        }
    }
    async initializeFormAnalysisTipsAndSupplements(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeFormAnalysisTipsAndSupplements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeFormAnalysisTipsAndSupplements();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logCaffeineIntake(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logCaffeineIntake(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logCaffeineIntake(arg0);
            return result;
        }
    }
    async logWeightProgress(arg0: ExerciseId, arg1: number, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWeightProgress(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWeightProgress(arg0, arg1, arg2);
            return result;
        }
    }
    async logWorkoutCompletion(arg0: RecordId, arg1: WorkoutPlanId, arg2: UserId, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkoutCompletion(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkoutCompletion(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async rejectConnectionRequest(arg0: ConnectionRequestId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectConnectionRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectConnectionRequest(arg0);
            return result;
        }
    }
    async removeUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUser(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveLocationPreference(arg0: number, arg1: number, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLocationPreference(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLocationPreference(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveTrainingPartnerPreference(arg0: Array<string>, arg1: string, arg2: Array<string>, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTrainingPartnerPreference(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTrainingPartnerPreference(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async sendConnectionRequest(arg0: UserId, arg1: string): Promise<ConnectionRequestId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendConnectionRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendConnectionRequest(arg0, arg1);
            return result;
        }
    }
    async updateBrandingSettings(arg0: BrandingSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBrandingSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBrandingSettings(arg0);
            return result;
        }
    }
    async updateExerciseInLibrary(arg0: ExerciseId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExerciseInLibrary(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExerciseInLibrary(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateWorkoutPlan(arg0: WorkoutPlanId, arg1: string, arg2: Array<Set_>, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkoutPlan(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkoutPlan(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_AppUserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUserRole): AppUserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ConnectionRequest_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConnectionRequest): ConnectionRequest {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ExerciseWithHistory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExerciseWithHistory): ExerciseWithHistory {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_User_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Exercise]): Exercise | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExerciseWithHistory]): ExerciseWithHistory | null {
    return value.length === 0 ? null : from_candid_ExerciseWithHistory_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_WeightProgressionEntry>]): Array<WeightProgressionEntry> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FormAnalysisTip]): FormAnalysisTip | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LocationPreference]): LocationPreference | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OptimalWorkoutTime]): OptimalWorkoutTime | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupplementStack]): SupplementStack | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrainingPartnerPreference]): TrainingPartnerPreference | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    role: _AppUserRole;
    email: string;
}): {
    id: UserId;
    name: string;
    role: AppUserRole;
    email: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_AppUserRole_n15(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _AppUserRole;
    email: string;
}): {
    name: string;
    role: AppUserRole;
    email: string;
} {
    return {
        name: value.name,
        role: from_candid_AppUserRole_n15(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userHistory: [] | [Array<_WeightProgressionEntry>];
    exercise: _Exercise;
}): {
    userHistory?: Array<WeightProgressionEntry>;
    exercise: Exercise;
} {
    return {
        userHistory: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.userHistory)),
        exercise: value.exercise
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConnectionRequestId;
    status: {
        pending: null;
    } | {
        rejected: null;
    } | {
        accepted: null;
    };
    receiverId: _UserId;
    message: string;
    timestamp: bigint;
    senderId: _UserId;
}): {
    id: ConnectionRequestId;
    status: Variant_pending_rejected_accepted;
    receiverId: UserId;
    message: string;
    timestamp: bigint;
    senderId: UserId;
} {
    return {
        id: value.id,
        status: from_candid_variant_n32(_uploadFile, _downloadFile, value.status),
        receiverId: value.receiverId,
        message: value.message,
        timestamp: value.timestamp,
        senderId: value.senderId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    admin: null;
} | {
    trainer: null;
}): AppUserRole {
    return "client" in value ? AppUserRole.client : "admin" in value ? AppUserRole.admin : "trainer" in value ? AppUserRole.trainer : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): Variant_pending_rejected_accepted {
    return "pending" in value ? Variant_pending_rejected_accepted.pending : "rejected" in value ? Variant_pending_rejected_accepted.rejected : "accepted" in value ? Variant_pending_rejected_accepted.accepted : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConnectionRequest>): Array<ConnectionRequest> {
    return value.map((x)=>from_candid_ConnectionRequest_n30(_uploadFile, _downloadFile, x));
}
function to_candid_AppUserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppUserRole): _AppUserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: AppUserRole;
    email: string;
}): {
    name: string;
    role: _AppUserRole;
    email: string;
} {
    return {
        name: value.name,
        role: to_candid_AppUserRole_n8(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppUserRole): {
    client: null;
} | {
    admin: null;
} | {
    trainer: null;
} {
    return value == AppUserRole.client ? {
        client: null
    } : value == AppUserRole.admin ? {
        admin: null
    } : value == AppUserRole.trainer ? {
        trainer: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
